export const pokemons=[
    {
        name:'bulbasaur',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png`
    },
    {
        name:'ivysaur',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png`
    },
    {
        name:'venusaur',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png`
    },
    {
        name:'charmander',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png`
    },
    {
        name:'charmeleon',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png`
    },
    {
        name:'charizard',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png`
    },
    {
        name:'squirtle',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png`
    },
    {
        name:'wartortle',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png`
    },
    {
        name:'caterpie',
        image:`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png`
    },
    
]